### ISSUE TITLE
Change default branch to develop

### ISSUE THREAD

**Issue by onedr0p** [getsops/sops#1013]
@ajvb would it make sense to set the default branch in the Github project settings to the `develop` branch? This would lead to less confusion on new PRs which want to be merged into the `master` branch by default. This would also lead to less confusion on the state of commits, as the develop branch is much more active.

**Comment by ajvb** [comment]
The problem with that (at least last time we looked into it, which was a while ago) was that `go get ...sops...` would then pull and install off of the `develop` branch. Same when used as a library.

If we can resolve that, then absolutely!

**Comment by onedr0p** [comment]
I am not sure if that is really an issue, people should really be pulling at specific tags e.g.

```
go get github.com/mozilla/sops@v3.7.1
```

or even

```
go get github.com/mozilla/sops@master
```

never...

```
go get github.com/mozilla/sops
```

**Comment by ajvb** [comment]
@onedr0p Agreed. As well, I hadn't been following the [deprecation of go get to install binaries](https://go.dev/doc/go-get-install-deprecation). I'd say once we upgrade to Go v1.17 (which will be in the next release), we should give this a try.

**Comment by onedr0p** [comment]
Closing in favor of #1238
