### ISSUE TITLE
sops --version (prevent phone home) 

### ISSUE THREAD

**Issue by veenarm** [getsops/sops#1100]
I'm running sops in a air-gapped area without internet access, running command sops --version / -v is making it wait for ages as it tries to go external...

[warning] failed to retrieve latest version from upstream: Get "https://raw.githubusercontent.com/mozilla/sops/master/version/version.go": dial tcp IP : i/o timeout

Is there a way to skip/prevent this?

**Comment by felixfontein** [comment]
This is something I've also been wondering. Third-party code that uses sops and supports multiple versions might want to be able to determine the sops version by calling `sops --version`, but right now that's basically a no-go thanks to that network request, which a) is a potential privacy violation, and b) is slow (compared to how fast `sops --version` could be without it), and c) can be extremely slow when network isn't available.

**Comment by felixfontein** [comment]
I created #1115 to add a flag which allows to disable this behavior.

**Comment by hiddeco** [comment]
This should have been addressed in https://github.com/getsops/sops/releases/tag/v3.8.0-rc.1. I would like to invite anyone to try this out, potential issues can be discussed in https://github.com/getsops/sops/discussions/1270.
