### ISSUE TITLE
Decrypt requires `.yml` extension?

### ISSUE THREAD

**Issue by calebTree** [getsops/sops#1112]
I noticed decrypt fails if the file I intend to decrypt has an extension other than `.yml` i.e. `test.yml.enc`.
```
Error unmarshalling input json: invalid character <whatever first char in file> looking for beginning of value
```

**Comment by felixfontein** [comment]
sops falls back to assuming the file is JSON encoded when no extension is present, which it is not in your case. You can tell sops that the file is a YAML file by supplying `--input-type yaml`.
