### ISSUE TITLE
AWS SSO is badly broken in SOPS

### ISSUE THREAD

**Issue by devonjones** [getsops/sops#1197]
I'm using the aws client 2 for logging into aws sso.  The config that aws sso uses where you declare an sso-session isn't respected, but further, even if you move the keys like sso_region and sso_start_url into the config for a specific profile, it then breaks on the cache.

**Comment by kruczjak** [comment]
Seems like sso-session is supported in `aws-sdk-go-v2` https://github.com/aws/aws-sdk-go-v2/pull/1903

Sops uses old "v1" version.

**Comment by kruczjak** [comment]
There is also draft PR with upgrade: https://github.com/mozilla/sops/pull/1179

**Comment by dzavalkin-scayle** [comment]
@hiddeco Please add this issue to [3.8.0 milestone](https://github.com/getsops/sops/milestone/5), since migration to AWS SDK v2 is done. Currently version of SOPS is not usable if one uses AWS SSO and has AWS CLI config set up per current AWS documentation...

**Comment by hiddeco** [comment]
The milestone tracks pull requests, and not issues. #1065 is on the list however.

**Comment by dzavalkin-scayle** [comment]
Thanks! I found a workaround to get sops working via converting AWS CLI config to legacy format (i.e. without named SSO session) but with `sso_start_url` and `sso_account_id` keys in each AWS CLI profile).

**Comment by hiddeco** [comment]
This should have been addressed in https://github.com/getsops/sops/releases/tag/v3.8.0-rc.1. I would like to invite anyone to try this out, potential issues can be discussed in https://github.com/getsops/sops/discussions/1270.

**Comment by devonjones** [comment]
confirmed, thanks!

**Comment by muhamedkapoevolt** [comment]
I had same issue, update resolved that. Thanks!!!
