### ISSUE TITLE
[Question] When do you plan to release a new version of the binary ?

### ISSUE THREAD

**Issue by jbdelpech** [getsops/sops#1253]
Hello,

We are expecting a new version of SOPS binary to benefit of new features like [AWS SSO support](https://github.com/getsops/sops/issues/1197).

When do you plan to release a new version of the binary ?

Thank you

**Comment by hiddeco** [comment]
Apologies for the delay. I understand your eagerness to see this become available. :bow: 

Unfortunately, we're unable to release a new version at this time. As the release automation relied on bits and pieces to which we no longer have access after change in stewardship.

I have painstakingly reconstructed and modernized the release process in #1250.  Once this is successfully implemented, and after addressing the remaining milestones for [`v3.8.0`](https://github.com/getsops/sops/pulls?q=is%3Aopen+is%3Apr+milestone%3Av3.8.0), , we will proceed with the release.

**Comment by jbdelpech** [comment]
Hi, thank you for the clarification 🙏
