### ISSUE TITLE
SOPS doesn't interact well with dotenv inline comments

### ISSUE THREAD

**Issue by johnmatthiggins** [getsops/sops#1271]
Say I have a dotenv file with the contents seen below:
```
ID="123#567"
```
I need the quotes to ensure that the javascript `dotenv` library can parse the field correctly. Without the quotes the value of the variable will become just "123" because the hash will be regarded as the start of a comment which will stop the parser from reading the rest of the value.

SOPS currently doesn't respect the quotes in my dotenv file. It strips them when encrypting then creates this file when decrypting which breaks dotenv:
```
ID=123#567
```

Would it be possible to wrap every value with a hash inside of it in quotes when decrypting a dotenv file?

**Comment by felixfontein** [comment]
I guess the main problem is that there is no "the" dotenv format. There are many different ones. (Similar to .ini files.)

The format as currently supported by sops is very primitive: comments must start at the beginning of a line, and every other line must contain a `=`, and the line is split at `=`. In the part after `=`, `\n` escapes a newline (but there is no escape for `\` itself), and quotes are not considered at all.

(I'm wondering why you say that the quotes are stripped. I don't see why that should happen from looking at the code.)

Please note that changing this is a **breaking change**. This was attempted earlier already: https://github.com/getsops/sops/commit/4507019a33518859c76cb54ec0eea6755c0b4b39 - and then reverted shortly after in #706.

**Comment by johnmatthiggins** [comment]
I think I may have been mistaken, it looks like it's a problem on my side. I was using `sops --set` and the bash script I was using to only encrypt changes to the .env file and not re-encrypt the whole thing was auto stripping the quotes.

Apologies for the confusion and thank you so much for the quick response.
