### ISSUE TITLE
sops 3.8.0 doesn't work with qubes split gpg

### ISSUE THREAD

**Issue by james-callahan** [getsops/sops#1294]
Cross posting from https://github.com/getsops/sops/pull/1054#issuecomment-1722630295

After upgrading to the new release, qubes split gpg (https://www.qubes-os.org/doc/split-gpg/ / https://github.com/QubesOS/qubes-app-linux-split-gpg) is no longer working.
I think this is due to the new release passing `--no-default-keyring` and `--homedir` which are both broken with qubes split gpg for different reasons:
  - `--no-default-keyring` is handled [here](https://github.com/QubesOS/qubes-app-linux-split-gpg/blob/ef64f62a882a2e62f31c06ab5e02cbe7e0dd1643/gpg-client-wrapper#L39-L40)
  - `--homedir` isn't handled at all, and it fails with `qubes-gpg-client: unrecognized option '--homedir'`

Also filed this issue with qubes: https://github.com/QubesOS/qubes-issues/issues/8523

**Comment by hiddeco** [comment]
SOPS is built with the official GnuPG binary in mind, and not with a wrapper offering a selective feature set. In my opinion, this should thus be solved on the Qubes side, as it would be hard for us to navigate every selective wrapper correctly.

**Comment by james-callahan** [comment]
From the linked qubes issue (https://github.com/QubesOS/qubes-issues/issues/8523#issuecomment-1722669637): 

> The option combination used by sops here looks weird - it adds `--no-default-keyring`, but does not specify any other keyring (so, no keyring should be used at all? decryption would fail then...). And then it specifies explicitly `--homedir`, to the value that is in fact the default one already.

@hiddeco are you able to explain what these arguments are meant to do?

**Comment by hiddeco** [comment]
After reading the man page again, it may look like we are able to drop `--no-default-keyring` but would continue to use `--homedir` (but potentially in combination with `--keyring`).

I wrote this code a long time ago, while it took some time to actually release it once we had settled stewardship. But they are intended to prevent reaching out to unexpected locations when a GnuPG home is set up for isolation: https://github.com/getsops/sops/blob/main/pgp/keysource.go#L114-L123

**Comment by james-callahan** [comment]
> After reading the man page again, it may look like we are able to drop `--no-default-keyring` but would continue to use `--homedir` (but potentially in combination with `--keyring`).

At least right now, it seems to pass my normal gnupg homedir: `--homedir /home/user/.gnupg`.
Why specify the `--homedir` argument when it already matches the default?

> they are intended to prevent reaching out to unexpected locations when a GnuPG home is set up for isolation: https://github.com/getsops/sops/blob/main/pgp/keysource.go#L114-L123

How does one activate that code path? At least here in the github UI I'm not seeing how that function gets called.

**Comment by hiddeco** [comment]
As you seem to have run into a dead end on the other side as well. I will see what we can do about preferring plain `gpg` calls without flags as much as possible from the CLI, but this will take a bit of time.
