### ISSUE TITLE
Missing sops-v3.8.0.linux?

### ISSUE THREAD

**Issue by lucasfcnunes** [getsops/sops#1296]
Is this intended? Were these fat or amd64 only?
https://github.com/getsops/sops/releases/download/v3.8.0/sops-v3.8.0.linux MISSING
https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux EXISTS
https://github.com/getsops/sops/releases/download/v3.7.2/sops-v3.7.2.linux EXISTS
...

**Comment by hiddeco** [comment]
The `.linux` was a duplicate of `.amd64`: https://github.com/getsops/sops/blob/v3.7.3/.github/workflows/release.yml#L38
