### ISSUE TITLE
Azure Default Credential Login fails since 3.8.0

### ISSUE THREAD

**Issue by mruoss** [getsops/sops#1316]
We're running the terraform provider https://github.com/carlpett/terraform-provider-sops inside a GitHub workflow. But I believe the issue is here rather than in the TF provider.

Since the latest upgrade of the provider which contains an upgrade to SOPS 3.8.0, authentication does not work anymore, although the `az login` worked and `AZURE_TENANT_ID` and `AZURE_CLIENT_ID` are set.

We're using Workload Identity (federated credentials) to authenticate GitHub with the Azure Key Vault.

Here's the output:

```
Error: Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED

  https://***redacted***.vault.azure.net/keys/sops-key/***redacted***: FAILED
    - | failed to decrypt sops data key with Azure Key Vault key
      | 'https://***redacted***.vault.azure.net/keys/sops-key/***redacted***':
      | DefaultAzureCredential authentication failed
      | GET http://169.254.169.254/metadata/identity/oauth2/token
      | --------------------------------------------------------------------------------
      | RESPONSE 400 Bad Request
      | --------------------------------------------------------------------------------
      | ***
      |   "error": "invalid_request",
      |   "error_description": "Identity not found"
      | ***
      | --------------------------------------------------------------------------------

...

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
  ```

**Comment by hiddeco** [comment]
You appear to be running into https://github.com/Azure/azure-sdk-for-go/issues/18352, which is not an issue with SOPS itself.

**Comment by mruoss** [comment]
Hmm... that was a bug solved in the azapi terraform provider. But that provider is used neither by us directly, nor by https://github.com/carlpett/terraform-provider-sops...

**Comment by hiddeco** [comment]
SOPS uses `NewDefaultAzureCredential(nil)` which should work in almost any scenario. Given this, the Terraform provider you are making use of probably has a similar issue as the provider mentioned in that thread, and solving this is very likely not a problem for us to address.

**Comment by mruoss** [comment]
The reason I've opened the issue here and not in the terraform provider is that these are literally the changes included in the new version of the TF provider: https://github.com/carlpett/terraform-provider-sops/compare/v0.7.2...v1.0.0

I just don't see a high chance of these changes breaking auth. And then on the other hand, the changes around Azure authentication in this repo are substantial. But then again, I've been using the default credentials of the official azure libraries in other languages (e.g. JS) and the tend to work just fine...

**Comment by hiddeco** [comment]
I think your problem is actually `AZURE_CLIENT_ID` (and likewise variables) being set. As I understand (from a quick read), the Azure login action authenticates the further workflow (outside of these environment variables).

Which means that if you try to set those variables again, `NewDefaultAzureCredential(nil)` will attempt to re-authenticate (which will fail) instead of falling back to the (already authenticated) CLI credentials.

**Comment by mruoss** [comment]
Ooooh yes indeed. I had this code in the workflow:

```yaml
      # Required for SOPS Provider:
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
```

Because BEFORE v3.8.0, these were actually required in order for workload identity auth to work (as your code was more custom tailored). Now that you're using the azure lib, these are actually in the way.  

I have removed them all => works like a charm.

Many thanks for the support. I was on the path of adding more of them (like `AZURE_AUTHORITY_HOST`) when I read your message.
