### ISSUE TITLE
totalvirus detects Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by papanito** [getsops/sops#1331]
the Maxsecure engine detects Trojan.Malware.300983.susgen in the latest versions (windows exe):
https://www.virustotal.com/gui/file/fe1f6299294b47ceda565e1091e843ee3f3db58764901d4298eb00558189e25f

![image](https://github.com/getsops/sops/assets/15034009/4cde42f5-01e4-447c-b102-b042af0cd789)

**Comment by hiddeco** [comment]
This is a notoriously false positive returned quite often by MaxSecure, and Googling `"maxsecure" "Trojan.Malware.300983.susgen"` (or `"maxsecure" "Suspicious.low.ml.score"`) will show you a dozen other projects for which this happened.

**Comment by papanito** [comment]
> This is a notoriously false positive returned quite often by MaxSecure, and Googling "maxsecure" "Trojan.Malware.300983.susgen" (or "maxsecure" "Suspicious.low.ml.score") will show you a dozen other projects for which this happened.

I am pretty sure it is a false positive, just to raise awareness
