### ISSUE TITLE
--mac-only-encrypted panics on .env files.

### ISSUE THREAD

**Issue by lancerushing** [getsops/sops#1353]
Thank you for --mac-only-encrypted  Works great on my .yaml files

However it panics on .env

```shell
$ sops -e --mac-only-encrypted sample.env
panic: interface conversion: interface {} is bool, not string

goroutine 1 [running]:
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitPlainFile(0xc00058e200?, {0xc000011110?, 0xc0005aae45?, 0xc0005aae45?})
        /home/lance/go/src/github.com/getsops/sops/stores/dotenv/store.go:130 +0x2bf
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitEncryptedFile(0xc0004e8680?, {{{0xdd1be8f, 0xedce9ddb7, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        /home/lance/go/src/github.com/getsops/sops/stores/dotenv/store.go:115 +0x3fc
main.encrypt({{0x1231d98, 0xc0004e4690}, {0x12389b0, 0x19bc1a0}, {0x12389b0, 0x19bc1a0}, {0xc000049ad0, 0x24}, {0xc0004daac0, 0x1, ...}, ...})
        /home/lance/go/src/github.com/getsops/sops/cmd/sops/encrypt.go:107 +0x575
main.main.func8(0xc0001898c0)
        /home/lance/go/src/github.com/getsops/sops/cmd/sops/main.go:808 +0xab8
github.com/urfave/cli.HandleAction({0xeb5880?, 0x110f8b0?}, 0xc0004756c0?)
        /home/lance/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc0004756c0, {0xc00003e0a0, 0x5, 0x5})
        /home/lance/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:286 +0x766
main.main()
        /home/lance/go/src/github.com/getsops/sops/cmd/sops/main.go:1014 +0x3530
```

I'm running 0cc1d116c47f0311c66f4bb348cf4026c130d275  (main HEAD from Nov 14)

**Comment by lancerushing** [comment]
I wrote a test duplicating the bug `dotenv/store_test.go`.  And I quickly coded up a type checker in `dotenv/store.go`.  :thinking:  But it *feels* wrong.   It feels like the `TreeItem` key of `sops_mac_only_encrypted` should be a string by the time it reaches `store.go` and not a bool.

**Comment by lancerushing** [comment]
I have a branch with a fix here:  https://github.com/lancerushing/sops/commit/934c2cd4a59b8362a112f51fc98c8b2447a71469

It is a quick fix for the cast issues in `dotenv.store.go` for `Metadata.MACOnlyEncrypted` being a `bool`.

:thinking:  Perhaps it would be better to make `Metadata.MACOnlyEncrypted` instead. (??)  Maybe not..

I do like idea of having more expressive types on `Metadata`.  However, the marshal code for dotenv (and ini?) will need to handle any non-string types.

**Comment by felixfontein** [comment]
CC @mitar

**Comment by mitar** [comment]
@felixfontein Thanks for CCing me.

@lancerushing Thanks for this report and suggested fix. I think you are right. Or we fix support for ini types or we change `Metadata.MACOnlyEncrypted` a string? (I think you are suggesting that, it seems like a sentence ends early there.)

@felixfontein What do you think? My personal take would be to fix parsing of ini metadata like @lancerushing did above.

**Comment by felixfontein** [comment]
I think I agree that fixing the parsing is the best approach here, and add support for new types and their fields when needed. (Having generic code for this would be nice, but seems a bit like overengineering right now.)

**Comment by lancerushing** [comment]
Maybe we should write a `dotenv` and `ini` marshaler for `Metadata`, and have annotations on the `Metadata` struct like we have for json and yaml. (???)

**Comment by mitar** [comment]
@lancerushing Are you are interested in writing that? Otherwise we might go with the simple fix for now and then if metadata grows into too much spaghetti code we could rewrite it?

**Comment by lancerushing** [comment]
Yeah I can stab at it tonight.

**Comment by lancerushing** [comment]
I also noticed that `dotenv` doesn't do the "complex" data types of `Metadata.KeyGroups`.  I could attempt to add support for that. 

We have to decide on an format that accommodate arrays in the dotenv.  Maybe an "index" suffix? `sops_keygoup_0...n`
 or  we could json enoode the key groups?  `sops_key_group=[{json here}, {}, ...]` :thinking: :thinking:

**Comment by lancerushing** [comment]
After looking through the code, both `ini` and `dotenv` have the panic for the `bool` `Metadata.MACOnlyEncrypted`.

Both use `stores.Unflatten()`.  Also `Flatten` and `Unflatten` are only used for metadata.  :thinking:  I have a couple ways I can add a fix. I'll do both, and see which one you prefer.

Option A) Quick fix:  I'll and a `func FixTypesForMetaData(in map[string]interface{}) map[string]interface{} `, and add it right after `stores.Unflatten(m)` in `dotenv/store.go` and `ini/store.go`.  Least amount of code, and it encapsulates the change neatly.

Option B) I'll change the signature of `Flatten` to `func Flatten(m store.Metadata) map[string]interface{}` and `Unflatten` to `func Unflatten(in map[string]interface{}) (Metadata, error) `.  This will eliminate the duplicate code in the `ini` and `dotenv` stores.

**Comment by lancerushing** [comment]
Option A - PR is here:  https://github.com/getsops/sops/pull/1355

Give me an hour (or so) and I'll have Option B ready

**Comment by lancerushing** [comment]
Option B - PR is here: https://github.com/getsops/sops/pull/1356

The casting is the same as  to Option A.  In additional I consolidated the json marshalling and \n handling into `stores/flatten.go`.  Plus wrote additional test.

**Comment by lancerushing** [comment]
Future: we probably should add some dotenv and ini tests into functional-tests.  For now after I ran `make install` I did a manual test in the shell.
```shell
export SOPS_AGE_RECIPIENTS="age1lzd99uklcjnc0e7d860axevet2cz99ce9pq6tzuzd05l5nr28ams36nvun"

echo "key = value" > example.env
echo "key = value" > example.ini

sops --encrypt --mac-only-encrypted example.env > example.encrypted.env
sops --encrypt --mac-only-encrypted example.ini > example.encrypted.ini

sops --decrypt example.encrypted.env > example.decrypted.env
sops --decrypt example.encrypted.ini > example.decrypted.ini

diff example.ini example.decrypted.ini
diff example.env example.decrypted.env
```

**Comment by mitar** [comment]
Awesome work, thanks!

**Comment by lancerushing** [comment]
I'm glad to help.  Let me know if you need anything else in the PRs.
