### ISSUE TITLE
GitHub repository does not link to the project website url

### ISSUE THREAD

**Issue by thisisobate** [getsops/sops#1395]
As part of our ongoing effort to [ensure all the websites within the CNCF meet the CLOMonitor guidelines](https://github.com/cncf/techdocs/issues/196), we noticed that sops does not pass the website criteria on [CLOMonitor](https://clomonitor.io/search?not_passing_check=website&foundation=cncf&page=1). 

To fix this:
Edit [getsops/sops](https://github.com/getsops/sops) repository details. See Notary for example: 
<img width="1704" alt="Screenshot 2023-11-22 at 09 29 19" src="https://github.com/notaryproject/notary/assets/29557702/0b9dd1e3-f32b-42c6-adfc-a860ebad347b">

In the website section, add the link to the sops website. See Notary for example:
<img width="1704" alt="Screenshot 2023-11-22 at 09 30 15" src="https://github.com/notaryproject/notary/assets/29557702/c883c1c3-f9d7-4fcc-ae3c-fadf402d43cd">

Once done, feel free to close this issue as CLOMonitor will recrawl the page and update accordingly.

**Comment by devstein** [comment]
@thisisobate Thanks for making an issue. Just updated it to https://getsops.io/
