### ISSUE TITLE
Flag --filename-override is not defined

### ISSUE THREAD

**Issue by mhemken-vts** [getsops/sops#1422]
The documentation says this:

---

To encrypt, it is important to note that SOPS also uses the filename to look up the correct creation rule from
``.sops.yaml``. Likely ``/dev/stdin`` will not match a creation rule, or only match the fallback rule without
``path_regex``, which is usually not what you want. For that, ``sops`` provides the ``--filename-override``
parameter which allows you to tell SOPS which filename to use to match creation rules:

.. code:: sh

	$ echo 'foo: bar' | sops --filename-override path/filename.sops.yaml --encrypt /dev/stdin > encrypted-data

---

But on sops version `sops 3.8.1 (latest)` and `sops 3.7.1` I get the error:

```
[CMD]    FATA[0000] flag provided but not defined: -filename-override
```

How do I make this work?

**Comment by felixfontein** [comment]
This is only availabe on the `main` branch on not yet in a release. You either have to build the latest version from the `main` branch and use that one, or wait for the 3.9.0 release.

**Comment by mhemken-vts** [comment]
Ah, ok I see. Sorry about that :)

**Comment by felixfontein** [comment]
No worries!
