### ISSUE TITLE
When we encrypt our values it updates all variables

### ISSUE THREAD

**Issue by nodkrot** [getsops/sops#1495]
This is problematic because its hard to see what was changed in git and it is very easy to make a mistake: For example if i forgot to decrypt latest values, i change something and then encrypt it will override all values with outdated information.

Is there a setting im missing?

**Comment by alainrk** [comment]
Hi @nodkrot could you provide an example to replicate the issue?

**Comment by nodkrot** [comment]
We ended up using `sops --set` which helps with diffing only changed variables. We have encrypted and decrypted files separate to avoid accidental commits with decrypted values for context.
