### ISSUE TITLE
Does sops edit exist?

### ISSUE THREAD

**Issue by julianschacher** [getsops/sops#1514]
Hi,

I'm just starting out with SOPS and playing around a bit.
I noticed that calling `sops edit testfile.yaml` doesn't create a `testfile.yaml`, but rather creates a file named `edit`. So my question is: Does a `sops edit` command actually exist?

**Comment by julianschacher** [comment]
Ahh, I'm sorry, those are available in an upcoming version and the README already reflects that. I'm sorry! Closing.

**Comment by felixfontein** [comment]
No worries, the current situation *is* very confusing... I hope that we'll have a new minor release soon with all the features on `main` (and the ones that are ready to merge) out soon...
