### ISSUE TITLE
encrypt & decrypt command format conflict 

### ISSUE THREAD

**Issue by Minahhh666** [getsops/sops#1541]
Hi I was trying to encrypt and decrypt files by following the instructions on readme using command like
`$ sops encrypt myfile.json`
`$ sops decrypt myfile.json`
but it didn't work and turned out I have to use
`$ sops --encrypt myfile.json`
`$ sops --decrypt myfile.json`
in order for it to work. FYI it was run on both Ubuntu and MacOS

**Comment by felixfontein** [comment]
See https://github.com/getsops/sops/discussions/1538, the README is for the current `main` branch version, subcommands are not available yet in a release.

**Comment by felixfontein** [comment]
SOPS 3.9.0 is now out, with that this now works: https://github.com/getsops/sops/releases/tag/v3.9.0
