### ISSUE TITLE
Sops cannot find config file if it's named .sops.yml (instead of .sops.yaml)

### ISSUE THREAD

**Issue by ErraticMaker** [getsops/sops#1567]
I don't know if it is a hard requirement that the sops config file is exactly `.sops.yaml` for it to be auto-discovered, or if it should accept the alternative `.yml` extension too, but it took me a while to realize this was the issue I was having.

So, it might be good to have a warning in the docs stating that it should match exactly to save some time to anyone facing the same issue. Or even better would be to allow the file to have either of those extensions.

I think the code where the name is defined to match that specific file name is [here](https://github.com/getsops/sops/blob/c921bf5e4d9339ce1e593fce7a575f55f0c262b4/config/config.go#L49) just for reference.

Thank you for the great work!

**Comment by felixfontein** [comment]
You can always use `--config` to specify your config file, then it doesn't matter at all how it is named.

> So, it might be good to have a warning in the docs stating that it should match exactly to save some time to anyone facing the same issue. Or even better would be to allow the file to have either of those extensions.

Mentioning that in the docs is the best way forward IMO; allowing `.yml` as well is something I would avoid.

**Comment by ErraticMaker** [comment]
Okay! Made a small PR (#1569). Feel free to leave comments or just replace it if you feel there is a better phrasing or place to put the note.
