### ISSUE TITLE
sops edit does not work

### ISSUE THREAD

**Issue by benkeil** [getsops/sops#1594]
The [examples](https://github.com/getsops/sops?tab=readme-ov-file#41creating-a-new-file) in the README does not work.

```
sops edit secret.yaml
sops edit --pgp C9CAB0AF1165060DB58D6D6B2653B624D620786D secret.yaml
```

outputs `Error: cannot operate on non-existent file` but should create a new file

**Comment by felixfontein** [comment]
Hmm, that's indeed a bug. Thanks for spotting it!

**Comment by felixfontein** [comment]
#1596 fixes it.

**Comment by felixfontein** [comment]
(As a work-around you can leave `edit` away, i.e. `sops secret.yaml` and `sops --pgp C9CAB0AF1165060DB58D6D6B2653B624D620786D secret.yaml`.)
