### ISSUE TITLE
Creation rules don't work on windows

### ISSUE THREAD

**Issue by SaymonPhoenix** [getsops/sops#1650]
Hi

I created a .sops.yaml file.

```
creation_rules:
  - path_regex: environments/dev/.*_secrets.yaml
    age: ***
```

This works fine on Linux, but when I try to call "sops -e environments/dev/app_secrets.yaml" on Windows I get an error - error loading config: no matching creation rules found.

Please help me

**Comment by felixfontein** [comment]
Check out #892 and #1036. SOPS normalizes the path and thus turns `/` into `\`, which doesn't match your regexp.

**Comment by SaymonPhoenix** [comment]
@felixfontein Thank you very much for the clarification. Strange and illogical behavior.

**Comment by felixfontein** [comment]
I agree. The problem is that it's tricky to change without breaking existing setups, see the discussion here: https://github.com/getsops/sops/pull/1523#discussion_r1634197631

**Comment by SaymonPhoenix** [comment]
@felixfontein I understand and I'm very sorry. I'll close the issue.
