### ISSUE TITLE
update kms to AWS SDK v2

### ISSUE THREAD

**Issue by st33v** [getsops/sops#850]
We're currently using AWS SSO for end user authentication. AWS SSO relies on functionality introduced in v2 of the AWS SDK and sops simply does not work. 

Our work around currently is to use [aws2-wrap](https://github.com/linaro-its/aws2-wrap). It works fine (as long as I remember to use the wrapper) but I thought I'd let you guys know about the issue and the work around.

**Comment by dpc** [comment]
I've pushed #1179 but I'm not sure if I'll be able to complete it.

**Comment by benley** [comment]
Is this already done?  It looks like it may have happened in May 2022: https://github.com/getsops/sops/pull/1065

**Comment by hiddeco** [comment]
This is available in v3.8.0.
