### ISSUE TITLE
Missed key for some encrypted files

### ISSUE THREAD

**Issue by Moskovych** [getsops/sops#977]
The issue with files (as example) like this:

https://github.com/mozilla/sops/blob/develop/stores/json/test_resources/example.json

File encrypted with GPG, where the FP: `E5297818703249D0C60E19E6824612478D1A4CCD`, which doesn't exist anywhere.

It is not possible to work on unit tests (for https://github.com/mozilla/sops/pull/887) without having that file decrypted.

Discussion: https://github.com/mozilla/sops/discussions/970

**Comment by felixfontein** [comment]
@Moskovych I was looking at this today to see whether I could simply generate a new file with known keys, but then I noticed that this file isn't used in the tests *at all*. So I created a PR (#1288) to simply delete it.

**Comment by Moskovych** [comment]
@felixfontein , hmm, now I'm a bit confused, where I should fix tests for my PR 😕

**Comment by felixfontein** [comment]
@Moskovych that's a very good question, it depends on what exactly is failing. GHA doesn't show the test results from back then anymore, unfortunately. Can you rebase (and also run `gofmt -w stores/json/store.go`) and force-push?
