### ISSUE TITLE
Please update docker image to the latest 3.7.1

### ISSUE THREAD

**Issue by haizaar** [getsops/sops#988]
Good day,

https://hub.docker.com/r/mozilla/sops/tags still lists 3.**6**.1 as the latest image.

Can you please release docker image for the latest 3.**7**.1 version?

**Comment by Enrico204** [comment]
FYI images have been updated :-)

**Comment by toabi** [comment]
This doesn't look automated? The latest v3 image contains `sops 3.7.3` but the repository here has a 3.8.1 release…

**Comment by hiddeco** [comment]
As we are no longer under Mozilla's umbrella, the actual container images can be found at either:

- https://github.com/getsops/sops/pkgs/container/sops/versions
- https://quay.io/repository/getsops/sops

They are also noted in the [release notes](https://github.com/getsops/sops/releases/tag/v3.8.1) under "container images".
